### ISSUE TITLE
Support multi path per directive

### ISSUE THREAD

**Issue by matsumotory** [matsumotory/mod_mruby#66]
I want to support multi path per directive like the following example:

``` apache
<Location />
  mrubyHandlerMiddleMulti /path/to/A.rb /path/to/B.rb /path/to/C.rb
</Location>
```

First, mod_mruby run `A.rb`. Then run `B.rb`, Finally run `C.rb` at mrubyHandlerMiddle phase.

**Comment by matsumoto-r** [comment]
Patches are welcome!!

**Comment by matsumoto-r** [comment]
```apache
<Location />
  mrubyHandlerMiddle a.rb [cache] b.rb [cache] ...
</Location>
```

it also looks good to me.
